import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import ResultsArea from "@/components/ResultsArea";
import SearchArea from "@/components/SearchArea";
import Hero from "@/components/Hero";
import { Beer } from "@/types/types";
import { GetServerSideProps } from "next";
import Link from "next/link";
import BeerCard from "@/components/BeerCard";

export const getServerSideProps: GetServerSideProps = async () => {
  console.log(`getServerSideProps`);

  const res = await fetch(
    `https://api.punkapi.com/v2/beers?page=1&per_page=80`
  );

  console.log(`getServerSideProp fetch`);

  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }: any) {
  const [searchInput, setSearchInput] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cyan-700">
        <Hero heading="Brewdog project" message="no idea what to write here yet :)" />
        <SearchArea
          searchInput={searchInput}
          setSearchResults={setSearchResults}
          pageNumber={pageNumber}
          setPageNumber={setPageNumber}
        />
        <div className="flex justify-center items-center p-10">
        <div className="flex flex-col justify-between items-center  lg:grid grid-cols-3 xl:grid-cols-3 h-full w-full bg-cyan-700 gap-4">
          {data?.map((el: Beer) => {
            return (
              <Link href={`/beers/${el.id}`} key={el.id}>
                <BeerCard
                  key={el.id}
                  name={el.name}
                  tagline={el.tagline}
                  abv={el.abv}
                  image_url={el.image_url}
                />
              </Link>
            );
          })}
          </div>
          </div>
      </main>
    </>
  );
}
