import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import ResultsArea from "@/components/ResultsArea";
import SearchArea from "@/components/SearchArea";

export default function Home() {
  const [searchInput, setSearchInput] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cyan-700">
        <SearchArea
          searchInput={searchInput}
          setSearchResults={setSearchResults}
          pageNumber={pageNumber}
          setPageNumber={setPageNumber}
        />
        <ResultsArea
          searchResults={searchResults}
          setSearchResults={setSearchResults}
          pageNumber={pageNumber}
          setPageNumber={setPageNumber}
        />
      </main>
    </>
  );
}
