import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import ResultsArea from "@/components/ResultsArea";
import SearchArea from "@/components/SearchArea";
import Hero from "@/components/Hero";
import { Beer } from "@/types/types";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async () => {
  console.log(`getServerSideProps`);

  const res = await fetch(
    `https://api.punkapi.com/v2/beers?page=1&per_page=30`
  );

  console.log(`getServerSideProp fetch`);

  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }: any) {
  const [searchInput, setSearchInput] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cyan-700">
        <Hero />
        <SearchArea
          searchInput={searchInput}
          setSearchResults={setSearchResults}
          pageNumber={pageNumber}
          setPageNumber={setPageNumber}
        />
        <ResultsArea
          data={data}
          searchResults={searchResults}
          setSearchResults={setSearchResults}
          pageNumber={pageNumber}
          setPageNumber={setPageNumber}
        />
      </main>
    </>
  );
}
